# Data processing

## Contents <a id=ov>
1. [Saving and Loading Data](#save)
2. [Numpy](#np)
3. [Saving and loading data into Pandas dataframe](#save_pandas)
4. [Investigate your Pandas dataframe](#Investigate)
5. [Pandas Series Object ](#series)
6. [Indexing and filtering](#filter)
7. [Plotting](#plt)
8. [Statsmodels](#sm)




## Saving and Loading Data <a id=save>
### Pickle
You can save or load every Python object via pickle:

In [1]:
import pickle

football_players={'Neymar':['PSG',29,100],
                  'Haaland':['BVB',21,150],
                  'Lukaku':['Chelsea',28,100],
                  'Messi':['PSG',34,80],
                  'Goretzka':['Bayern',26,70],
                  'Salah':['Liverpool',29,100],
                  'Kane':['Tottenham',28,120],
                  'Folden':['ManU',21,80]}
#saving
pickle.dump(football_players,open('football_players.p','wb'))
print('football_players.p','saved!')

football_players.p saved!


In [2]:
#load
football_players=pickle.load(open('football_players.p','rb'))
print(football_players)

{'Neymar': ['PSG', 29, 100], 'Haaland': ['BVB', 21, 150], 'Lukaku': ['Chelsea', 28, 100], 'Messi': ['PSG', 34, 80], 'Goretzka': ['Bayern', 26, 70], 'Salah': ['Liverpool', 29, 100], 'Kane': ['Tottenham', 28, 120], 'Folden': ['ManU', 21, 80]}


### JSON files
The best way to save datasets with consist of dictionaries, list, strings and numericals  is ***JSON***, because it is readable for humans and other programming languages:


In [11]:
import json
#save
with open('football_players.json','w') as file:
    json.dump(football_players,file)

#load
with open('football_players.json') as json_object:
    python_object=json.load(json_object)

print(python_object)

{'Neymar': ['PSG', 29, 100], 'Haaland': ['BVB', 21, 150], 'Lukaku': ['Chelsea', 28, 100], 'Messi': ['PSG', 34, 80], 'Goretzka': ['Bayern', 26, 70], 'Salah': ['Liverpool', 29, 100], 'Kane': ['Tottenham', 28, 120], 'Folden': ['ManU', 21, 80]}


### XML files
XML files can be parse with Beautifulsoup. For large files, however, treating the file als text using ``open()`` and searching for keys with string methods can be more efficient.

## Numpy <a id=np>
[Back to Content Overview](#ov)

Numpy is the Python library for vector/matrix operations. Most of the import packages in data science and machine learning.

In [59]:
import numpy as np

### Basics
You can define a vector/matrix in the following way:

In [13]:
test_vector=np.array([[1,4,5],[7,3,6]])
print(type(test_vector))
print(test_vector)

<class 'numpy.ndarray'>
[[1 4 5]
 [7 3 6]]


In [14]:
# Get the dimensions of the array:
print(np.shape(test_vector))

(2, 3)


In [15]:
# Transpose the array:
print(test_vector.transpose())
print(test_vector.T)

[[1 7]
 [4 3]
 [5 6]]
[[1 7]
 [4 3]
 [5 6]]


In [16]:
# Change the shape of the array
print(np.array(range(0,10)).reshape((2,5)))

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Special Arrays:

In [17]:
# Array with zeros:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
# Array with ones:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# Array with range of numbers:
print(np.arange(10))
print(np.array(range(10))) # Similar

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [20]:
# Array with equally distributed numbers in a interval
print(np.linspace(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


#### Random:

In [21]:
# Array with random numbers between 0 and 1:
print(np.random.random(size=5))

[0.07482675 0.33289289 0.61428056 0.65526511 0.433252  ]


In [22]:
# Array with random integers
print(np.random.randint(0,10,size=200))

[9 5 9 6 8 3 9 1 1 7 6 8 8 2 1 8 7 1 8 1 4 3 1 5 9 3 2 1 0 5 8 8 1 2 0 5 9
 1 5 2 5 6 2 4 7 1 4 0 5 7 4 2 1 1 8 1 0 9 6 8 2 9 6 1 5 8 9 9 7 1 0 8 4 8
 4 8 8 0 4 4 7 9 6 3 1 4 9 7 3 2 2 0 6 8 8 4 0 1 9 2 5 4 2 3 0 6 5 4 2 5 1
 4 4 0 8 1 7 1 1 7 7 5 3 4 3 5 9 3 0 8 8 0 1 6 3 8 9 2 1 2 7 6 2 4 4 9 9 6
 1 8 0 9 9 2 3 3 8 3 4 0 5 1 2 0 2 2 5 1 3 7 8 8 6 5 6 3 0 9 2 9 9 7 5 8 6
 0 2 9 9 6 0 2 1 6 6 0 9 6 8 5]


In [24]:
# Array with normal dist. random numbers:
print(np.random.normal(loc=0.0, scale=1.0, size=6))

[  0.95645957 -28.72909033  -8.61100949  45.17685863  45.19857741
 -38.76986381]


#### Indexing:

In [25]:
test_vector=np.array([[1,4,5,6],[7,3,6,3],[3,3,1,9]])
print(test_vector)

[[1 4 5 6]
 [7 3 6 3]
 [3 3 1 9]]


In [26]:
# Print frist row
print(test_vector[0,:])

[1 4 5 6]


In [27]:
# Print last column
print(test_vector[:,-1])

[6 3 9]


<span style="color:blue"><b>Task:</b></span> Print the 2x2 matrix in the lower, right corner.

In [30]:
print(test_vector[-2:,-2:])

n_rows,n_cols=np.shape(test_vector)
print(n_rows)
print(n_cols)

[[6 3]
 [1 9]]
3
4


<span style="color:blue"><b>Task:</b></span> Create a  4x4 identity matrix!

In [31]:
# Use a for loop!
matrix=np.zeros((4,4))
for i in range(4):
    matrix[i,i]=1
    
print(matrix)




[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [32]:
matrix=np.zeros((4,4))

for i in range(4):
    for j in range(4):
        if i==j:
            matrix[i,j]=1
print(matrix)            
            

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [33]:
# Use a the diagonal method!
matrix=np.diag([1,1,1,1])
print(matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [34]:
matrix=np.diag(np.ones(100))
print(matrix)


[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [35]:
matrix=np.diag([1]*100)
print(matrix)

[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


In [39]:
# Use a the method numpy method provides for you!
matrix=np.identity(4)
print(matrix)
matrix=np.eye(4,4)
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


You can also index arrays with booleans:

In [41]:
print(test_vector)

print(test_vector>3)
print(test_vector[test_vector>3])

[[1 4 5 6]
 [7 3 6 3]
 [3 3 1 9]]
[[False  True  True  True]
 [ True False  True False]
 [False False False  True]]
[4 5 6 7 6 9]


In [48]:
vector=np.array([1,3,4,5,2,np.nan,53])

print(vector)
print(np.sum(vector))

print(~np.isnan(vector))
print(vector[~np.isnan(vector)])
vector=vector[~np.isnan(vector)]
print(np.sum(vector))

[ 1.  3.  4.  5.  2. nan 53.]
nan
[ True  True  True  True  True False  True]
[ 1.  3.  4.  5.  2. 53.]
68.0


#### Stacking
You can also stack vector or matrices horizontally or vertically :

In [49]:
test_vector=np.array([[1,4,5],[7,3,6]])
print(test_vector)

[[1 4 5]
 [7 3 6]]


In [50]:
#Stack horizontally:
print(np.hstack((test_vector,test_vector)))

[[1 4 5 1 4 5]
 [7 3 6 7 3 6]]


In [51]:
#Stack vertically:
print(np.vstack((test_vector,test_vector)))

[[1 4 5]
 [7 3 6]
 [1 4 5]
 [7 3 6]]


#### Sorting:

In [60]:
sort_vector=np.random.randint(0,10,size=20)
print(sort_vector)

[0 0 2 8 4 6 8 6 4 8 4 0 7 3 8 9 0 2 2 5]


In [53]:
# Sort vector
print(np.sort(sort_vector))

[0 0 0 1 1 1 2 2 3 4 5 5 5 6 7 7 8 8 8 9]


In [54]:
# Gives back the new indices of the elements if the vector would be sorted:
print(np.argsort(sort_vector))

[15  4 13 17  2 14  6 11 18  9 12 19  5  7 10  0  3 16  1  8]


In [55]:
print(sort_vector[np.argsort(sort_vector)])

[0 0 0 1 1 1 2 2 3 4 5 5 5 6 7 7 8 8 8 9]


In [58]:
names=np.array(['Tom','Huy','Mukta','Aniqua'])

age=np.array([26,32,23,99])

print(np.sort(names))

print(np.argsort(age))

print(names[np.argsort(age)])

['Aniqua' 'Huy' 'Mukta' 'Tom']
[2 0 1 3]
['Mukta' 'Tom' 'Huy' 'Aniqua']


In [56]:
# You can use if to sort an vector with order of an other vector:
sort_vector_2=np.random.randint(0,10,size=20)
print(sort_vector_2)
print(sort_vector_2[np.argsort(sort_vector)])

[8 6 4 6 8 7 6 5 7 1 6 3 1 8 2 1 0 7 8 6]
[1 8 8 7 4 2 6 3 8 1 1 6 7 5 6 8 6 0 6 7]


In [61]:
#There are also function to find the minimum or maximum value of vector:
print(np.max(sort_vector))
print(np.min(sort_vector))
print(np.argmax(sort_vector))
print(np.argmin(sort_vector))

9
0
15
0


#### Mathematical functions:

There are all standard (and not so standard)  [mathematical functions](https://numpy.org/doc/stable/reference/routines.math.html) in numpy:

In [62]:
test_vector=np.array([[1,4,5,6],[7,3,6,3],[3,3,1,9]])
print(test_vector)

[[1 4 5 6]
 [7 3 6 3]
 [3 3 1 9]]


In [63]:
#Total sum
print(np.sum(test_vector))

51


In [64]:
#Sum for every column
print(np.sum(test_vector,axis=0))

[11 10 12 18]


In [65]:
#Sum for every row
print(np.sum(test_vector,axis=1))

[16 19 16]


<span style="color:blue"><b>Task:</b></span> Calculate the mean for the first two rows steperately. (2 Versions)

In [71]:
#print(test_vector[0,:].mean())
print(np.mean(test_vector[:2,:],axis=1))

[4.   4.75]


In [76]:
print(np.mean(test_vector,axis=1)[:2])

[4.   4.75]


In [77]:
# You also apply the stand math operators on numpy arrays:
print(test_vector*2)
print(test_vector%3)

[[ 2  8 10 12]
 [14  6 12  6]
 [ 6  6  2 18]]
[[1 1 2 0]
 [1 0 0 0]
 [0 0 1 0]]


In [78]:
print(np.var(test_vector,axis=0)**0.5)
print(np.std(test_vector,axis=0))

[2.49443826 0.47140452 2.1602469  2.44948974]
[2.49443826 0.47140452 2.1602469  2.44948974]


In [79]:
print(np.sin(test_vector))
print(np.cos(test_vector))
print(np.tan(test_vector))

[[ 0.84147098 -0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.14112001 -0.2794155   0.14112001]
 [ 0.14112001  0.14112001  0.84147098  0.41211849]]
[[ 0.54030231 -0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.9899925   0.96017029 -0.9899925 ]
 [-0.9899925  -0.9899925   0.54030231 -0.91113026]]
[[ 1.55740772  1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -0.14254654 -0.29100619 -0.14254654]
 [-0.14254654 -0.14254654  1.55740772 -0.45231566]]


<span style="color:blue"><b>Task:</b></span> Rebuild this numpy.sin function with a for loop.

In [81]:
sin_results=np.ones(np.shape(test_vector))
print(sin_results)
import math

nrows,ncols=np.shape(test_vector)

for i in range(nrows):
    for j in range(ncols):
        sin_results[i,j]=math.sin(test_vector[i,j])

print(sin_results)
print (math.sin(0.00))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 0.84147098 -0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.14112001 -0.2794155   0.14112001]
 [ 0.14112001  0.14112001  0.84147098  0.41211849]]
0.0


<span style="color:blue"><b>Task:</b></span> Calculate the sum of squares for every column.

In [83]:
print(np.sum(test_vector**2,axis=0))

[ 59  34  62 126]


<span style="color:blue"><b>Task:</b></span> Standardise the test_vector.

In [84]:
print((test_vector-np.mean(test_vector))/np.std(test_vector))

[[-1.40455069 -0.10804236  0.32412708  0.75629653]
 [ 1.18846597 -0.5402118   0.75629653 -0.5402118 ]
 [-0.5402118  -0.5402118  -1.40455069  2.05280486]]


In [86]:
print(np.mean(test_vector,axis=0))
print(np.std(test_vector,axis=0))

print((test_vector-np.mean(test_vector,axis=0))/np.std(test_vector,axis=0))


[3.66666667 3.33333333 4.         6.        ]
[2.49443826 0.47140452 2.1602469  2.44948974]
[[-1.06904497  1.41421356  0.46291005  0.        ]
 [ 1.33630621 -0.70710678  0.9258201  -1.22474487]
 [-0.26726124 -0.70710678 -1.38873015  1.22474487]]


#### Other functions

In [89]:
test_vector=np.array([[1,4,5,6],[7,3,6,3],[3,3,1,9]])
test_vector_2=np.array([[4,2,9,1],[7,4,6,3],[2,4,1,9]])

print(test_vector)
print(test_vector_2)

[[1 4 5 6]
 [7 3 6 3]
 [3 3 1 9]]
[[4 2 9 1]
 [7 4 6 3]
 [2 4 1 9]]


In [90]:
# Use where to apply condition on vectors.
print(np.where(test_vector>=test_vector_2,test_vector,np.nan))

# Use where to apply condition on vectors.
print(np.where(test_vector>=test_vector_2,test_vector,test_vector_2))

[[nan  4. nan  6.]
 [ 7. nan  6.  3.]
 [ 3. nan  1.  9.]]
[[4 4 9 6]
 [7 4 6 3]
 [3 4 1 9]]


In [91]:
# Use unique to delete duplicates and retrun the counts.
print(np.unique(test_vector,return_counts=True))

(array([1, 3, 4, 5, 6, 7, 9]), array([2, 4, 1, 1, 2, 1, 1], dtype=int64))


In [92]:
unique_vector,counts=np.unique(test_vector,return_counts=True)
print(unique_vector)
print(counts)

[1 3 4 5 6 7 9]
[2 4 1 1 2 1 1]


<span style="color:blue"><b>Task:</b></span> Sort the unique values with its counts in descending order.

In [98]:
print(np.argsort(-counts))

print(unique_vector[np.argsort(-counts)])

[1 0 4 2 3 5 6]
[3 1 6 4 5 7 9]


## Saving and loading data into Pandas dataframe <a id=savepandas>
[Back to Content Overview](#ov)

In [99]:
import pandas as pd

The mean object of the pandas module is the dataframe. A datatable with named rows and columns:

In [101]:
#Import data from a matrix
column_names=['column_'+str(i) for i in range(0,4)]
print(column_names)
df=pd.DataFrame(data=test_vector,columns=column_names,index=None)

['column_0', 'column_1', 'column_2', 'column_3']


In [102]:
print(df)
print(df.index,list(df.index))
print(df.columns)

   column_0  column_1  column_2  column_3
0         1         4         5         6
1         7         3         6         3
2         3         3         1         9
RangeIndex(start=0, stop=3, step=1) [0, 1, 2]
Index(['column_0', 'column_1', 'column_2', 'column_3'], dtype='object')


In [103]:
#You can change the indices and columns via:
df.index=[1,2,3]
df.columns=['one','two','three','four']

print(df)

   one  two  three  four
1    1    4      5     6
2    7    3      6     3
3    3    3      1     9


In [104]:
#You access columns similar to dict value:
print(df['one'])

print(list(df['one']))

1    1
2    7
3    3
Name: one, dtype: int32
[1, 7, 3]


In [105]:
for col in df.columns:
    print(df[col])

1    1
2    7
3    3
Name: one, dtype: int32
1    4
2    3
3    3
Name: two, dtype: int32
1    5
2    6
3    1
Name: three, dtype: int32
1    6
2    3
3    9
Name: four, dtype: int32


### Importing and saving data

In [106]:
#Import data from a nested_list
df=pd.DataFrame(data=[[1,4,5,6],[7,3,6,3],[3,3,1,9]],columns=None,index=None)
print(df)


   0  1  2  3
0  1  4  5  6
1  7  3  6  3
2  3  3  1  9


In [107]:
#Import data from a dict
data_dict={'col1':[1,4,5,6],'col2':[7,3,6,3],'col3':[3,3,1,9]}
df=pd.DataFrame(data=data_dict)
print(df)

   col1  col2  col3
0     1     7     3
1     4     3     3
2     5     6     1
3     6     3     9


In [111]:
#Import data from a dict
data_dict={'col1':{'ind1':23,'ind1':1,'ind3':'string'},'col2':{'ind1':89,'ind3':'string'},'col3':{'ind3':'hello','ind4':"hello"}}
print(data_dict['col1'])
data_dict['col1']['ind1']=688
df=pd.DataFrame(data=data_dict)
print(df)

{'ind1': 1, 'ind3': 'string'}
        col1    col2   col3
ind1     688      89    NaN
ind3  string  string  hello
ind4     NaN     NaN  hello


In [112]:
#Save as csv
df.to_csv('test_df.csv')

In [115]:
#Save as pickle
df.to_pickle('test_df.pickle')

In [114]:
import sys
!{sys.executable} -m pip install openpyxl
#Save as excel
df.to_excel('test_df.xlsx')


[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
<ipython-input-114-88084a4c7b68>:4: UserWarning: Pandas requires version '1.4.3' or newer of 'xlsxwriter' (version '1.3.8' currently installed).
  df.to_excel('test_df.xlsx')


## Investigate your Pandas dataframe <a id=Investigate>
[Back to Content Overview](#ov)

In [158]:
#Import data from a excel_file
df=pd.read_excel('top_500_football_players.xlsx',sheet_name='final')
print(df)

       #          Player            Position  Age Market value  Matches  \
0      1   Kylian Mbappé      Centre-Forward   22    €160.00m        11   
1      2  Erling Haaland      Centre-Forward   21    €150.00m         8   
2      3      Harry Kane      Centre-Forward   28    €120.00m        10   
3      4   Jack Grealish         Left Winger   26    €100.00m        10   
4      5   Mohamed Salah        Right Winger   29    €100.00m         9   
..   ...             ...                 ...  ...          ...      ...   
495  496      Tom Davies    Central Midfield   23     €18.00m         5   
496  497   Hans Hateboer          Right-Back   27     €18.00m         0   
497  498      David Raya          Goalkeeper   26     €18.00m         7   
498  499    Gregor Kobel          Goalkeeper   23     €18.00m        12   
499  500  Wilmar Barrios  Defensive Midfield   27     €18.00m        10   

     Goals  Own goals  Assists  Yellow cards  Yellow red cards  Red cards  \
0        4          0 

In [117]:
#Show all columns names
print(df.columns)

Index(['#', 'Player', 'Position', 'Age', 'Market value', 'Matches', 'Goals',
       'Own goals', 'Assists', 'Yellow cards', 'Yellow red cards', 'Red cards',
       'Substitutions on', 'Substitutions off'],
      dtype='object')


In [118]:
#Show all row names
print(df.index)

RangeIndex(start=0, stop=500, step=1)


In [121]:
#Show the ten most valueable players
print(df.head(10))

    #           Player            Position  Age Market value  Matches  Goals  \
0   1    Kylian Mbappé      Centre-Forward   22    €160.00m        11      4   
1   2   Erling Haaland      Centre-Forward   21    €150.00m         8     11   
2   3       Harry Kane      Centre-Forward   28    €120.00m        10      6   
3   4    Jack Grealish         Left Winger   26    €100.00m        10      2   
4   5    Mohamed Salah        Right Winger   29    €100.00m         9      9   
5   6    Romelu Lukaku      Centre-Forward   28    €100.00m         9      4   
6   7  Kevin De Bruyne  Attacking Midfield   30    €100.00m         7      2   
7   8           Neymar         Left Winger   29    €100.00m         7      1   
8   9     Jadon Sancho         Left Winger   21     €90.00m         9      0   
9  10  Frenkie de Jong    Central Midfield   24     €90.00m         8      0   

   Own goals  Assists  Yellow cards  Yellow red cards  Red cards  \
0          0        5             2                

In [122]:
#Show Mr. Irrelevant
print(df.tail(1))

       #          Player            Position  Age Market value  Matches  \
499  500  Wilmar Barrios  Defensive Midfield   27     €18.00m        10   

     Goals  Own goals  Assists  Yellow cards  Yellow red cards  Red cards  \
499      0          0        0             0                 0          0   

     Substitutions on  Substitutions off  
499                 0                  2  


In [123]:
#Show the data types of columns
print(df.dtypes)

#                     int64
Player               object
Position             object
Age                   int64
Market value         object
Matches               int64
Goals                 int64
Own goals             int64
Assists               int64
Yellow cards          int64
Yellow red cards      int64
Red cards             int64
Substitutions on      int64
Substitutions off     int64
dtype: object


In [124]:
#Count the data types of columns
print(df.dtypes.value_counts())

int64     11
object     3
dtype: int64


In [125]:
#Count the age of the players
print(df['Age'].value_counts())

24    73
25    55
23    51
26    48
28    45
27    44
22    41
21    33
29    30
30    26
20    19
19     9
18     9
31     8
33     3
32     3
36     1
34     1
16     1
Name: Age, dtype: int64


In [127]:
#Show all players with age 36
print(df[df['Age']==18]['Player'])

16                 Pedri
27       Jude Bellingham
42         Florian Wirtz
48             Ansu Fati
65     Eduardo Camavinga
76         Jamal Musiala
112       Giovanni Reyna
274         Ilaix Moriba
343         Rayan Cherki
Name: Player, dtype: object


In [128]:
#Show the most important informations of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   #                  500 non-null    int64 
 1   Player             500 non-null    object
 2   Position           500 non-null    object
 3   Age                500 non-null    int64 
 4   Market value       500 non-null    object
 5   Matches            500 non-null    int64 
 6   Goals              500 non-null    int64 
 7   Own goals          500 non-null    int64 
 8   Assists            500 non-null    int64 
 9   Yellow cards       500 non-null    int64 
 10  Yellow red cards   500 non-null    int64 
 11  Red cards          500 non-null    int64 
 12  Substitutions on   500 non-null    int64 
 13  Substitutions off  500 non-null    int64 
dtypes: int64(11), object(3)
memory usage: 54.8+ KB


In [129]:
#Show the most important statistics of the dataframe
df.describe()

#         Age    Matches       Goals   Own goals     Assists  \
count  500.000000  500.000000  500.00000  500.000000  500.000000  500.000000   
mean   250.500000   24.966000    7.62600    1.316000    0.012000    0.910000   
std    144.481833    3.191428    3.12885    1.976856    0.108994    1.274814   
min      1.000000   16.000000    0.00000    0.000000    0.000000    0.000000   
25%    125.750000   23.000000    6.00000    0.000000    0.000000    0.000000   
50%    250.500000   25.000000    8.00000    1.000000    0.000000    0.000000   
75%    375.250000   27.000000   10.00000    2.000000    0.000000    1.000000   
max    500.000000   36.000000   17.00000   13.000000    1.000000    7.000000   

       Yellow cards  Yellow red cards  Red cards  Substitutions on  \
count    500.000000        500.000000  500.00000        500.000000   
mean       0.966000          0.026000    0.02200          1.426000   
std        1.052168          0.159295    0.14683          1.740858   
min        0.000000          0.000000    0.00000          0.000000   
25%        0.000000          0.000000    0.00000          0.000000   
50%        1.000000          0.000000    0.00000          1.000000   
75%        1.000000          0.000000    0.00000          2.000000   
max        6.000000          1.000000    1.00000          9.000000   

       Substitutions off  
count         500.000000  
mean            2.352000  
std             2.286165  
min             0.000000  
25%             0.000000  
50%             2.000000  
75%             4.000000  
max            15.000000

<span style="color:blue"><b>Task:</b></span> Replicate df.disscribe! Hint: Use numpy to calcalate the statistical measures. 

In [138]:

result_dict={}

for col in df.columns:

    col_series=df[col]
    
    if pd.api.types.is_numeric_dtype(col_series):
        #print(col_series)
    
        col_dict={'count':col_series.count(),
                  'mean':col_series.mean(),
                  'std':col_series.std(),
                  'min':col_series.min(),
                  '25%':col_series.quantile(0.25),
                  '50%':col_series.quantile(0.5),
                  '75%':col_series.quantile(0.75),
                  'max':col_series.max()}
        
        result_dict[col]=col_dict
    
df_discribe=pd.DataFrame(result_dict)

df_discribe






#         Age    Matches       Goals   Own goals     Assists  \
count  500.000000  500.000000  500.00000  500.000000  500.000000  500.000000   
mean   250.500000   24.966000    7.62600    1.316000    0.012000    0.910000   
std    144.481833    3.191428    3.12885    1.976856    0.108994    1.274814   
min      1.000000   16.000000    0.00000    0.000000    0.000000    0.000000   
25%    125.750000   23.000000    6.00000    0.000000    0.000000    0.000000   
50%    250.500000   25.000000    8.00000    1.000000    0.000000    0.000000   
75%    375.250000   27.000000   10.00000    2.000000    0.000000    1.000000   
max    500.000000   36.000000   17.00000   13.000000    1.000000    7.000000   

       Yellow cards  Yellow red cards  Red cards  Substitutions on  \
count    500.000000        500.000000  500.00000        500.000000   
mean       0.966000          0.026000    0.02200          1.426000   
std        1.052168          0.159295    0.14683          1.740858   
min        0.000000          0.000000    0.00000          0.000000   
25%        0.000000          0.000000    0.00000          0.000000   
50%        1.000000          0.000000    0.00000          1.000000   
75%        1.000000          0.000000    0.00000          2.000000   
max        6.000000          1.000000    1.00000          9.000000   

       Substitutions off  
count         500.000000  
mean            2.352000  
std             2.286165  
min             0.000000  
25%             0.000000  
50%             2.000000  
75%             4.000000  
max            15.000000

In [145]:
result_dict={'count':df.count(numeric_only=True),
                  'mean':df.mean(numeric_only=True),
                  'std':df.std(numeric_only=True),
                  'min':df.min(numeric_only=True),
                  '25%':df.quantile(0.25,numeric_only=True),
                  '50%':df.quantile(0.5,numeric_only=True),
                  '75%':df.quantile(0.75,numeric_only=True),
                  'max':df.max(numeric_only=True)}
df_discribe=pd.DataFrame(result_dict,index=df.select_dtypes([np.number]).columns).transpose()
#df_discribe=pd.DataFrame.from_dict(result_dict,orient='index',columns=df.select_dtypes([np.number]).columns)

df_discribe

#         Age    Matches       Goals   Own goals     Assists  \
count  500.000000  500.000000  500.00000  500.000000  500.000000  500.000000   
mean   250.500000   24.966000    7.62600    1.316000    0.012000    0.910000   
std    144.481833    3.191428    3.12885    1.976856    0.108994    1.274814   
min      1.000000   16.000000    0.00000    0.000000    0.000000    0.000000   
25%    125.750000   23.000000    6.00000    0.000000    0.000000    0.000000   
50%    250.500000   25.000000    8.00000    1.000000    0.000000    0.000000   
75%    375.250000   27.000000   10.00000    2.000000    0.000000    1.000000   
max    500.000000   36.000000   17.00000   13.000000    1.000000    7.000000   

       Yellow cards  Yellow red cards  Red cards  Substitutions on  \
count    500.000000        500.000000  500.00000        500.000000   
mean       0.966000          0.026000    0.02200          1.426000   
std        1.052168          0.159295    0.14683          1.740858   
min        0.000000          0.000000    0.00000          0.000000   
25%        0.000000          0.000000    0.00000          0.000000   
50%        1.000000          0.000000    0.00000          1.000000   
75%        1.000000          0.000000    0.00000          2.000000   
max        6.000000          1.000000    1.00000          9.000000   

       Substitutions off  
count         500.000000  
mean            2.352000  
std             2.286165  
min             0.000000  
25%             0.000000  
50%             2.000000  
75%             4.000000  
max            15.000000

## Pandas Series Object <a id=series>
[Back to Content Overview](#ov)

Every column of a dataframe is a Pandas Series Object.

In [146]:
print(df['Age'])

0      22
1      21
2      28
3      26
4      29
       ..
495    23
496    27
497    26
498    23
499    27
Name: Age, Length: 500, dtype: int64


In [147]:
print(type(df['Age']))

<class 'pandas.core.series.Series'>


You can also define them manually:

In [148]:
test_series = pd.Series(range(3,16))
print(test_series)

0      3
1      4
2      5
3      6
4      7
5      8
6      9
7     10
8     11
9     12
10    13
11    14
12    15
dtype: int64


In [149]:
# You also give them a name:
test_series.name = 'Magic Series'
print(test_series)

0      3
1      4
2      5
3      6
4      7
5      8
6      9
7     10
8     11
9     12
10    13
11    14
12    15
Name: Magic Series, dtype: int64


Series have some specifc functions ...

In [150]:
print(test_series.sum())
print(test_series.mean())
print(test_series.value_counts())

117
9.0
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: Magic Series, dtype: int64


... but you can also tread them as numpy vectors and apply every numpy function on them:

In [151]:
print(np.sum(test_series))
print(np.sum(test_series[test_series**2>20]))

117
110


In [152]:
# Add the new column to the dataframe
df['Scorer Points']=df['Goals']+df['Assists']
print(df.head(10))

    #           Player            Position  Age Market value  Matches  Goals  \
0   1    Kylian Mbappé      Centre-Forward   22    €160.00m        11      4   
1   2   Erling Haaland      Centre-Forward   21    €150.00m         8     11   
2   3       Harry Kane      Centre-Forward   28    €120.00m        10      6   
3   4    Jack Grealish         Left Winger   26    €100.00m        10      2   
4   5    Mohamed Salah        Right Winger   29    €100.00m         9      9   
5   6    Romelu Lukaku      Centre-Forward   28    €100.00m         9      4   
6   7  Kevin De Bruyne  Attacking Midfield   30    €100.00m         7      2   
7   8           Neymar         Left Winger   29    €100.00m         7      1   
8   9     Jadon Sancho         Left Winger   21     €90.00m         9      0   
9  10  Frenkie de Jong    Central Midfield   24     €90.00m         8      0   

   Own goals  Assists  Yellow cards  Yellow red cards  Red cards  \
0          0        5             2                

<span style="color:blue"><b>Task:</b></span> Add a new column with goals per game to the df!

In [155]:
df['Goals_per_Game']=df['Goals']/df['Matches']
print(df['Goals_per_Game'])
df['Goals_per_Game']=np.where(df['Matches']==0,0,df['Goals']/df['Matches'])
print(df['Goals_per_Game'])

0      0.363636
1      1.375000
2      0.600000
3      0.200000
4      1.000000
         ...   
495    0.000000
496         NaN
497    0.000000
498    0.000000
499    0.000000
Name: Goals_per_Game, Length: 500, dtype: float64
0      0.363636
1      1.375000
2      0.600000
3      0.200000
4      1.000000
         ...   
495    0.000000
496    0.000000
497    0.000000
498    0.000000
499    0.000000
Name: Goals_per_Game, Length: 500, dtype: float64


You can also apply list comprehensions on series objects:

In [168]:
df['Last Name']= [name.split(' ')[-1] for name in df['Player']]
print(df['Last Name'])

Player
Kylian Mbappé       Mbappé
Erling Haaland     Haaland
Harry Kane            Kane
Jack Grealish     Grealish
Mohamed Salah        Salah
                    ...   
Tom Davies          Davies
Hans Hateboer     Hateboer
David Raya            Raya
Gregor Kobel         Kobel
Wilmar Barrios     Barrios
Name: Last Name, Length: 500, dtype: object


<span style="color:blue"><b>Task:</b></span> Convert the market value to a type float:

In [162]:
print(df['Market value'])
df['Market_value']= [float(str(value).replace('€','').replace('m','')) for value in df['Market value']]

print(df['Market_value'])

0      €160.00m 
1      €150.00m 
2      €120.00m 
3      €100.00m 
4      €100.00m 
         ...    
495     €18.00m 
496     €18.00m 
497     €18.00m 
498     €18.00m 
499     €18.00m 
Name: Market value, Length: 500, dtype: object
0      160.0
1      150.0
2      120.0
3      100.0
4      100.0
       ...  
495     18.0
496     18.0
497     18.0
498     18.0
499     18.0
Name: Market_value, Length: 500, dtype: float64


In [160]:
df['Market_value'] =[float(str(value)[1:-2]) for value in df['Market value']]
print(df['Market_value'])

0      160.0
1      150.0
2      120.0
3      100.0
4      100.0
       ...  
495     18.0
496     18.0
497     18.0
498     18.0
499     18.0
Name: Market_value, Length: 500, dtype: float64


## Indexing and filtering <a id=filter>
[Back to Content Overview](#ov)

In [166]:
df.index=df['Player']
print(df)

                  #          Player            Position  Age Market value  \
Player                                                                      
Kylian Mbappé     1   Kylian Mbappé      Centre-Forward   22    €160.00m    
Erling Haaland    2  Erling Haaland      Centre-Forward   21    €150.00m    
Harry Kane        3      Harry Kane      Centre-Forward   28    €120.00m    
Jack Grealish     4   Jack Grealish         Left Winger   26    €100.00m    
Mohamed Salah     5   Mohamed Salah        Right Winger   29    €100.00m    
...             ...             ...                 ...  ...          ...   
Tom Davies      496      Tom Davies    Central Midfield   23     €18.00m    
Hans Hateboer   497   Hans Hateboer          Right-Back   27     €18.00m    
David Raya      498      David Raya          Goalkeeper   26     €18.00m    
Gregor Kobel    499    Gregor Kobel          Goalkeeper   23     €18.00m    
Wilmar Barrios  500  Wilmar Barrios  Defensive Midfield   27     €18.00m    

<span style="color:blue"><b>Task:</b></span> Restore the old index.

In [178]:
df.index=range(len(df))
print(df)

       #          Player            Position  Age Market value  Matches  \
0      1   Kylian Mbappé      Centre-Forward   22    €160.00m        11   
1      2  Erling Haaland      Centre-Forward   21    €150.00m         8   
2      3      Harry Kane      Centre-Forward   28    €120.00m        10   
3      4   Jack Grealish         Left Winger   26    €100.00m        10   
4      5   Mohamed Salah        Right Winger   29    €100.00m         9   
..   ...             ...                 ...  ...          ...      ...   
495  496      Tom Davies    Central Midfield   23     €18.00m         5   
496  497   Hans Hateboer          Right-Back   27     €18.00m         0   
497  498      David Raya          Goalkeeper   26     €18.00m         7   
498  499    Gregor Kobel          Goalkeeper   23     €18.00m        12   
499  500  Wilmar Barrios  Defensive Midfield   27     €18.00m        10   

     Goals  Own goals  Assists  Yellow cards  Yellow red cards  Red cards  \
0        4          0 

In [169]:
# Query Columns with brackets and Column Name
print(df['Last Name'])
# Query a element with  Column Name and vector index
print(df['Last Name'][3])

Player
Kylian Mbappé       Mbappé
Erling Haaland     Haaland
Harry Kane            Kane
Jack Grealish     Grealish
Mohamed Salah        Salah
                    ...   
Tom Davies          Davies
Hans Hateboer     Hateboer
David Raya            Raya
Gregor Kobel         Kobel
Wilmar Barrios     Barrios
Name: Last Name, Length: 500, dtype: object
Grealish


### loc
Use loc to get elements with their row and column names:

In [170]:
# Get values for Salah
df.loc['Mohamed Salah',:]

#                                5
Player               Mohamed Salah
Position              Right Winger
Age                             29
Market value             €100.00m 
Matches                          9
Goals                            9
Own goals                        0
Assists                          3
Yellow cards                     1
Yellow red cards                 0
Red cards                        0
Substitutions on                 0
Substitutions off                2
Market_value                 100.0
Last Name                    Salah
Name: Mohamed Salah, dtype: object

<span style="color:blue"><b>Task:</b></span> Get Salahs Age:

In [171]:
df.loc['Mohamed Salah','Age']

29

### iloc
Use iloc to get elements with their row and column indices:

In [172]:
# Get values for most valuable player
df.iloc[0,:]

#                                 1
Player                Kylian Mbappé
Position             Centre-Forward
Age                              22
Market value              €160.00m 
Matches                          11
Goals                             4
Own goals                         0
Assists                           5
Yellow cards                      2
Yellow red cards                  0
Red cards                         0
Substitutions on                  0
Substitutions off                 5
Market_value                  160.0
Last Name                    Mbappé
Name: Kylian Mbappé, dtype: object

<span style="color:blue"><b>Task:</b></span> Get the last column for the ten most valuable players:

In [180]:
df.iloc[df['Market_value'].nlargest(10).index.values,-1]

df.iloc[:10,-1]

0      Mbappé
1     Haaland
2        Kane
3    Grealish
4       Salah
5      Lukaku
6      Bruyne
7      Neymar
8      Sancho
9        Jong
Name: Last Name, dtype: object

### filter

You can filter the dataframe with conditions similar to the numpy vectors:

In [181]:
# Only keep players with had at least one game
df_filter=df[df['Matches']>0]
print(df_filter)

       #          Player            Position  Age Market value  Matches  \
0      1   Kylian Mbappé      Centre-Forward   22    €160.00m        11   
1      2  Erling Haaland      Centre-Forward   21    €150.00m         8   
2      3      Harry Kane      Centre-Forward   28    €120.00m        10   
3      4   Jack Grealish         Left Winger   26    €100.00m        10   
4      5   Mohamed Salah        Right Winger   29    €100.00m         9   
..   ...             ...                 ...  ...          ...      ...   
494  495     Diego Rossi         Left Winger   23     €18.00m         7   
495  496      Tom Davies    Central Midfield   23     €18.00m         5   
497  498      David Raya          Goalkeeper   26     €18.00m         7   
498  499    Gregor Kobel          Goalkeeper   23     €18.00m        12   
499  500  Wilmar Barrios  Defensive Midfield   27     €18.00m        10   

     Goals  Own goals  Assists  Yellow cards  Yellow red cards  Red cards  \
0        4          0 

In [182]:
# Only keep players who are under 25 and have an market values over 50 mio:
df['Market value'] = [float(value.replace('€','').replace('m','')) for value in df['Market value']]
df_filter=df[(df['Age']<25) & (df['Market value']>50)] # use | for or
print(df_filter)

     #                  Player            Position  Age  Market value  \
0    1           Kylian Mbappé      Centre-Forward   22         160.0   
1    2          Erling Haaland      Centre-Forward   21         150.0   
8    9            Jadon Sancho         Left Winger   21          90.0   
9   10         Frenkie de Jong    Central Midfield   24          90.0   
13  14         Marcus Rashford         Left Winger   23          85.0   
16  17                   Pedri    Central Midfield   18          80.0   
17  18              João Félix      Second Striker   21          80.0   
18  19              Phil Foden    Central Midfield   21          80.0   
19  20        Lautaro Martínez      Centre-Forward   24          80.0   
22  23             Mason Mount  Attacking Midfield   22          75.0   
23  24        Matthijs de Ligt         Centre-Back   22          75.0   
24  25  Trent Alexander-Arnold          Right-Back   23          75.0   
25  26              Rúben Dias         Centre-Back 

You can also use list comprehensions with booleans to takle more complicated conditions:

<span style="color:blue"><b>Task:</b></span> Only keep players with a middle name. (Name consists of more than 2 words.)

In [189]:
print(df[[len(name.split(' '))>2 for name in df['Player']]])

#df_filter=df[]

       #                 Player            Position  Age  Market value  \
6      7        Kevin De Bruyne  Attacking Midfield   30         100.0   
9     10        Frenkie de Jong    Central Midfield   24          90.0   
23    24       Matthijs de Ligt         Centre-Back   22          75.0   
54    55     José María Giménez         Centre-Back   26          60.0   
62    63  Marc-André ter Stegen          Goalkeeper   29          60.0   
73    74        Virgil van Dijk         Centre-Back   30          55.0   
91    92         Stefan de Vrij         Centre-Back   29          50.0   
138  139        Rodrigo de Paul    Central Midfield   27          40.0   
187  188      Wissam Ben Yedder      Centre-Forward   31          35.0   
245  246       Emile Smith Rowe  Attacking Midfield   21          28.0   
275  276   Silas Katompa Mvumpa      Right Midfield   23          25.0   
285  286   Charles De Ketelaere      Centre-Forward   20          25.0   
295  296   André Zambo Anguissa  Defen

Use ``df.drop_duplicates()`` to delete duplicates from your dataset:

In [190]:
print(df.drop_duplicates())

       #          Player            Position  Age  Market value  Matches  \
0      1   Kylian Mbappé      Centre-Forward   22         160.0       11   
1      2  Erling Haaland      Centre-Forward   21         150.0        8   
2      3      Harry Kane      Centre-Forward   28         120.0       10   
3      4   Jack Grealish         Left Winger   26         100.0       10   
4      5   Mohamed Salah        Right Winger   29         100.0        9   
..   ...             ...                 ...  ...           ...      ...   
495  496      Tom Davies    Central Midfield   23          18.0        5   
496  497   Hans Hateboer          Right-Back   27          18.0        0   
497  498      David Raya          Goalkeeper   26          18.0        7   
498  499    Gregor Kobel          Goalkeeper   23          18.0       12   
499  500  Wilmar Barrios  Defensive Midfield   27          18.0       10   

     Goals  Own goals  Assists  Yellow cards  Yellow red cards  Red cards  \
0        4

<span style="color:blue"><b>Task:</b></span> Only show the player with the highest market value for every age.

In [192]:
print(df.drop_duplicates(subset=['Age']))

       #              Player            Position  Age  Market value  Matches  \
0      1       Kylian Mbappé      Centre-Forward   22         160.0       11   
1      2      Erling Haaland      Centre-Forward   21         150.0        8   
2      3          Harry Kane      Centre-Forward   28         120.0       10   
3      4       Jack Grealish         Left Winger   26         100.0       10   
4      5       Mohamed Salah        Right Winger   29         100.0        9   
6      7     Kevin De Bruyne  Attacking Midfield   30         100.0        7   
9     10     Frenkie de Jong    Central Midfield   24          90.0        8   
10    11     Bruno Fernandes  Attacking Midfield   27          90.0       11   
13    14     Marcus Rashford         Left Winger   23          85.0        0   
16    17               Pedri    Central Midfield   18          80.0        5   
21    22        Lionel Messi        Right Winger   34          80.0        5   
28    29     Alphonso Davies           L

<span style="color:blue"><b>Task:</b></span> Only show the player with the lowest market value for every age.

In [194]:
print(df.drop_duplicates(subset=['Age'],keep="last"))

       #              Player            Position  Age  Market value  Matches  \
21    22        Lionel Messi        Right Winger   34          80.0        5   
111  112   Cristiano Ronaldo      Centre-Forward   36          45.0        7   
343  344        Rayan Cherki  Attacking Midfield   18          23.0       10   
456  457               Portu        Right Winger   29          20.0        9   
459  460      Julian Draxler         Left Winger   28          20.0        9   
461  462          Jordi Alba           Left-Back   32          20.0        4   
462  463      Sergio Canales  Attacking Midfield   30          20.0        8   
464  465      Ángel Di María        Right Winger   33          20.0        6   
465  466      Miralem Pjanic    Central Midfield   31          20.0        5   
475  476        Noni Madueke        Right Winger   19          18.0       15   
478  479      William Saliba         Centre-Back   20          18.0       11   
480  481   Youssoufa Moukoko      Centre

Use ``df.sample()`` to get a random sample form your dataset:

In [202]:
# Choose 5 players randomly from the datasset
print(df.sample(5).iloc[:,:6])

       #               Player            Position  Age  Market value  Matches
126  127         Carlos Soler    Central Midfield   24          40.0        6
219  220          Joan Jordán    Central Midfield   27          30.0        9
61    62              Alisson          Goalkeeper   29          60.0        9
381  382       Berat Djimsiti         Centre-Back   28          22.0        9
163  164  Aurélien Tchouaméni  Defensive Midfield   21          35.0       15


<span style="color:blue"><b>Task:</b></span> Choose 10% of the df.

In [206]:
print(df.sample(frac=0.1))

print(df.sample(int(len(df)*0.01)))

       #                Player     Position  Age  Market value  Matches  \
346  347  Konstantinos Manolas  Centre-Back   30          23.0        5   
54    55    José María Giménez  Centre-Back   26          60.0        8   
484  485           Axel Disasi  Centre-Back   23          18.0       12   
121  122         Wesley Fofana  Centre-Back   20          40.0        0   
308  309       Davide Calabria   Right-Back   24          25.0        7   

     Goals  Own goals  Assists  Yellow cards  Yellow red cards  Red cards  \
346      0          0        0             2                 0          0   
54       0          0        0             3                 0          0   
484      1          0        0             2                 0          0   
121      0          0        0             0                 0          0   
308      1          0        1             0                 0          0   

     Substitutions on  Substitutions off  Market_value Last Name  
346                

### Group by



In [207]:
print(df.groupby(['Position']).mean())

                             #        Age  Market value   Matches     Goals  \
Position                                                                      
Attacking Midfield  241.731707  24.365854     36.804878  7.926829  1.853659   
Central Midfield    231.337838  25.054054     36.702703  7.351351  0.864865   
Centre-Back         250.735632  24.839080     33.137931  7.597701  0.252874   
Centre-Forward      235.507463  25.716418     38.194030  7.865672  3.567164   
Defensive Midfield  258.317073  25.048780     34.292683  7.731707  0.609756   
Goalkeeper          300.681818  26.227273     32.818182  7.909091  0.000000   
Left Midfield       317.000000  23.142857     29.285714  7.285714  1.571429   
Left Winger         230.404255  24.319149     40.234043  8.170213  1.680851   
Left-Back           242.750000  25.333333     33.875000  6.333333  0.458333   
Right Midfield      293.333333  25.333333     25.666667  4.666667  0.000000   
Right Winger        253.434783  24.391304     34.043

<ipython-input-207-bc6787cb8a63>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  print(df.groupby(['Position']).mean())


In [ ]:
<span style="color:blue"><b>Task:</b></span> Show the mean market value for each position for each age.

In [210]:
print(df.groupby(['Position','Age'])['Market value'].mean())
print(df.groupby(['Position','Age']).mean()['Market value'])

Position            Age
Attacking Midfield  18     45.000000
                    20     20.000000
                    21     22.666667
                    22     51.750000
                    23     34.250000
                             ...    
Second Striker      22     20.000000
                    23     25.000000
                    27     40.000000
                    30     41.500000
                    32     30.000000
Name: Market value, Length: 138, dtype: float64
Position            Age
Attacking Midfield  18     45.000000
                    20     20.000000
                    21     22.666667
                    22     51.750000
                    23     34.250000
                             ...    
Second Striker      22     20.000000
                    23     25.000000
                    27     40.000000
                    30     41.500000
                    32     30.000000
Name: Market value, Length: 138, dtype: float64


<ipython-input-210-fa03719d83e8>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  print(df.groupby(['Position','Age']).mean()['Market value'])


In [ ]:
<span style="color:blue"><b>Task:</b></span> Add a new column to the df with the mean market value respective to the position (Use a list comprehension)

In [214]:
df_helper=df.groupby(['Position']).mean()['Market value']
print(df_helper)
df['Position mean']=[df_helper[position] for position in df['Position']] 

print(df['Position mean'])

Position
Attacking Midfield    36.804878
Central Midfield      36.702703
Centre-Back           33.137931
Centre-Forward        38.194030
Defensive Midfield    34.292683
Goalkeeper            32.818182
Left Midfield         29.285714
Left Winger           40.234043
Left-Back             33.875000
Right Midfield        25.666667
Right Winger          34.043478
Right-Back            28.515152
Second Striker        39.750000
Name: Market value, dtype: float64
0      38.194030
1      38.194030
2      38.194030
3      40.234043
4      34.043478
         ...    
495    36.702703
496    28.515152
497    32.818182
498    32.818182
499    34.292683
Name: Position mean, Length: 500, dtype: float64


<ipython-input-214-0b33374e6f58>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_helper=df.groupby(['Position']).mean()['Market value']


<span style="color:blue"><b>Task:</b></span> Apply Position Fixed Effects

In [217]:
df['MV_FE']=df['Market value']- df['Position mean']
print(df['MV_FE'])

print(df['MV_FE'].var()/df['Market value'].var())

0      121.805970
1      111.805970
2       81.805970
3       59.765957
4       65.956522
          ...    
495    -18.702703
496    -10.515152
497    -14.818182
498    -14.818182
499    -16.292683
Name: MV_FE, Length: 500, dtype: float64
0.9744711626924575
